### ISSUE TITLE
Event handler is not greenlet ?

### ISSUE THREAD

**Issue by k4ml** [EvoluxBR/greenswitch#10]
I try to do this in my code:-

```
playback_queue = gevent.queue.Queue()

def on_playback_stop(event):
    print(event.headers.get('Event-Name'))
    uuid = event.headers.get('variable_uuid')
    event_name = event.headers.get('Event-Name')
    playback_queue.put((uuid, event_name, event))
    print("added to queue")

def on_channel_park(event):
    #print(event.headers)
    uuid = event.headers.get('variable_uuid')
    resp = fs.send('api uuid_answer %s' % uuid)
    print(resp.headers)
    print(resp.data)
    resp = fs.send("sendmsg %s\ncall-command: execute\nexecute-app-name: playback\nexecute-app-arg: http://www.noiseaddicts.com/samples_1w72b820/17.mp3" % uuid)
    print(resp.headers)
    #print(resp.data)

    print("Waiting for playback_stop")
    if not playback_queue.empty():
        _uuid, event = playback_queue.get()
        if uuid == _uuid:
            print("hanging up ...")
            resp = fs.send("sendmsg %s\ncall-command: hangup" % uuid)
            #print(resp.data)
            print(_uuid, event.headers)

        gevent.sleep(1)

    gevent.sleep(1)
    print("Waiting for playback_stop")
    if not playback_queue.empty():
        _uuid, event = playback_queue.get()
        if uuid == _uuid:
            print("hanging up ...")
            resp = fs.send("sendmsg %s\ncall-command: hangup" % uuid)
            #print(resp.data)
            print(_uuid, event.headers)

    print(gevent.getcurrent())
    gevent.sleep(1)
```

But look like `on_playback_stop()` only executed after `on_channel_park()` finished running.

**Comment by k4ml** [comment]
So I changed this:-

```
def _safe_exec_handler(self, handler, event):
        try:
            gevent.spawn(handler, event)
            #handler(event)
        except:
            logging.exception('ESL %s raised exception.' % handler.__name__)
            logging.error(pprint.pformat(event.headers))
```

and it seem to work, though I have to `sleep(10)`, otherwise it still get executed in serial.

**Comment by k4ml** [comment]
It make more sense now, (when the event handler running under greenlet):-

```
def on_playback_stop(event):
    print(event.headers.get('Event-Name'))
    uuid = event.headers.get('variable_uuid')
    event_name = event.headers.get('Event-Name')
    playback_queue.put((uuid, event_name, event))
    print("added to queue")

def on_channel_park(event):
    uuid = event.headers.get('variable_uuid')
    resp = fs.send('api uuid_answer %s' % uuid)
    print(resp.headers)
    print(resp.data)
    resp = fs.send("sendmsg %s\ncall-command: execute\nexecute-app-name: playback\nexecute-app-arg: http://www.noiseaddicts.com/samples_1w72b820/17.mp3" % uuid)

    print("Waiting for playback_stop")
    while True:
        try:
            _uuid, event_name, event = playback_queue.get()
        except gevent.queue.Empty:
            print("queue empty")
            continue

        if uuid == _uuid:
            print("hanging up ...")
            resp = fs.send("sendmsg %s\ncall-command: hangup" % uuid)
            print(resp.data)
            break
            #print(_uuid, event.headers)

    print(gevent.getcurrent())
```

**Comment by italorossi** [comment]
Hi, thanks for reaching out.

We already have a process_event greenlet that calls all the handlers, one at a time popped from an internal gevent queue, that's how it's supposed to work and I designed it that way. Note that your change will increase infinitely the number of running greenlets, for example if you put a handler for CHANNEL_EXECUTE, which happens a lot, you'll spawn a greenlet for every event parsed, 10000 events = 10000 greenlets. You can imagine what's next..

I'm not sure what you're trying to accomplish but adding that spawn call definitely won't solve it, that's why you needed to sleep(10), which is: "wait for all my other stuff running and them run this".

What are you trying to accomplish exactly?

**Comment by k4ml** [comment]
Thanks. That what I'm worrying about. What I need is to wait for playback_stop in channel_park. This is to avoid doing the logic in on_playback_stop(), thus spreading the call handling logic in multiple places. Originally, the idea came from https://github.com/fiorix/eventsocket/blob/master/examples/server.tac#L46.

Currently we handle the call using normal python thread (we use the esl lib that came with fs), where each event handler run in separate thread. It quickly get messy as we have the logic all over the place. The idea of handling the call in serial logic look nice to me, and much easier to explain.

Btw after spawning the event handler, I don't need sleep() anymore. `playback_queue.get()` I guess handle the switching control back to the scheduler so it work as expected. But as you said, it's not scalable solution, so I appreciate if you have different suggestion.

**Comment by italorossi** [comment]
Got it.

You initiate the playback after getting the park event? I can't imagine a way to accomplish that in a sync way.

I would do something like:

```python
playback_stop = gevent.event.Event()

def on_playback_stop(event):
    playback_stop.set()

def on_channel_park(event):
    gevent.spawn(wait_for_playback, event.headers.get('variable_uuid'))
    resp = fs.send("sendmsg %s\ncall-command: execute\nexecute-app-name: playback\nexecute-app-arg: http://www.noiseaddicts.com/samples_1w72b820/17.mp3" % uuid)

def wait_for_playback(uuid):
    playback_stop.wait(timeout=5)
    print('Playback stoped')
    resp = fs.send("sendmsg %s\ncall-command: hangup" % uuid)
```

The main diference here is that you spawn a greenlet only when getting the channel_park event, that means you know for that specific call you'll need to wait without blocking the event handler. It's a new greenlet but not for all the events.

**Comment by k4ml** [comment]
Correct me I'm wrong but this will only work if there's only one call at a time ? Because `gevent.event.Event()` being instantiated in the global scope, and `.set()` only work as binary switch, you can't send any argument to indicate which call uuid to invoke.

**Comment by k4ml** [comment]
So I put the event in a dict, keyed by the uuid:-

```
import gevent
import greenswitch

events = {}

def on_playback_stop(event):
    uuid = event.headers.get('variable_uuid')
    if uuid in events:
        events[uuid]['playback_stop'].set()

def on_channel_park(event):
    uuid = event.headers.get('variable_uuid')
    if uuid not in events:
        events[uuid] = {}

    events[uuid]['playback_stop'] = gevent.event.Event()

    print(event.headers.get('Caller-Destination-Number'))
    resp = fs.send("sendmsg %s\ncall-command: execute\nexecute-app-name: ring_ready\nexecute-app-arg: " % uuid)
    resp = fs.send("sendmsg %s\ncall-command: execute\nexecute-app-name: sleep\nexecute-app-arg: 5500" % uuid)
    gevent.sleep(5)
    resp = fs.send('api uuid_answer %s' % uuid)
    print(resp.headers)
    print(resp.data)
    gevent.spawn(wait_for_playback, uuid)
    resp = fs.send("sendmsg %s\ncall-command: execute\nexecute-app-name: playback\nexecute-app-arg: http://www.noiseaddicts.com/samples_1w72b820/17.mp3" % uuid)

def wait_for_playback(uuid):
    sess = events.get(uuid, None)
    if sess is None:
        return

    playback_stop = sess['playback_stop']
    playback_stop.wait(timeout=5)
    print('Playback stoped')
    resp = fs.send("sendmsg %s\ncall-command: hangup" % uuid)
    del(events[uuid])
```

**Comment by italorossi** [comment]
Can we close this?

**Comment by italorossi** [comment]
Hey @k4ml , thanks for updating here. If you have any other feedback please let me know. I'm using greenswitch in very specific scenarios and for now it's fine for my needs, but I'm open to new ideas and features and your feedback will be very appreciated.
