### ISSUE TITLE
Simple ESL lib based on greenswitch code

### ISSUE THREAD

**Issue by kerbsx** [EvoluxBR/greenswitch#11]
Hi, in my effort to learn about ESL and freeswitch, I try to implement pure python esl based on greenswitch code but without the gevent and event handlers stuff. Basically mimicking the ESL lib that come from freeswitch. Thanks to your work, I learned a lot in understanding async programming and why we need gevent for much easier event handling.

https://github.com/kerbsx/fs/wiki/Building-Application-with-FreeSwitch:-Python-socket

**Comment by italorossi** [comment]
Thanks for your feedback. I'm glad our project helped you to learn and congrats for your findings. Hope you keep learning and come back with contributions!

Cheers 👍
