### ISSUE TITLE
AttributeError on connect with Python 3.6.0

### ISSUE THREAD

**Issue by dedayoa** [EvoluxBR/greenswitch#12]
Hello,
I have used greenswitch in the past, with an older version of python.
However, after installing the latest version of greenswitch with Python 3.6.0, I get 
`
Traceback (most recent call last):
  File "C:\Users\dayo_bf\envs\python\biznum\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Users\dayo_bf\envs\python\biznum\lib\site-packages\greenswitch\esl.py", line 87, in receive_events
    self.handle_event(event)
  File "C:\Users\dayo_bf\envs\python\biznum\lib\site-packages\greenswitch\esl.py", line 128, in handle_event
    event.parse_data(data)
  File "C:\Users\dayo_bf\envs\python\biznum\lib\site-packages\greenswitch\esl.py", line 33, in parse_data
    headers[key.strip()] = value.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
Sun Aug  6 12:32:10 2017 <Greenlet at 0x5898260: <bound method InboundESL.receive_events of <greenswitch.esl.InboundESL object at 0x05100D10>>> failed with AttributeError
`
after running connect()
Your help will be appreciated

**Comment by italorossi** [comment]
Hi.

Thanks for reaching out.

Can you make sure you're able to connect to this ESL server through telnet?

telnet freeswitchip 8021

auth ClueCon



Em dom, 6 de ago de 2017 às 07:34, Dayo Ayeni <notifications@github.com>
escreveu:

**Comment by dedayoa** [comment]
Hello @italorossi,
Can't connect via telnet. Entering telnet fsip 8021 returns with 
`Content-Type: text/rude-rejection
                                 Content-Length: 24

                                                   Access Denied, go away.
                                                                          Content-Type: text/disconnect-notice
                                                                                                              Content-Length: 67

        Disconnected, goodbye.
                              See you at ClueCon! http://www.cluecon.com/`
It seems FS is blocking the attempt.
I should add that I'm using FusionPBX and I'm currently looking through the configs to see what may be refusing the connection attempt.

**Comment by dedayoa** [comment]
Hello @italorossi ,
So I fixed it. Thanks for the help.
I had assumed that by setting ES to listen on 0.0.0.0, it would automatically allow connections in. Turns out according to http://lists.freeswitch.org/pipermail/freeswitch-users/2015-September/115848.html, I had to define apply-inbound-acl in my config. Once I created an acl to "allow" 0.0.0.0, I was able to connect.

**Comment by italorossi** [comment]
Cool. Leave this opened. I'll cover this case and raise a proper exception.
Em dom, 6 de ago de 2017 às 09:37, Dayo Ayeni <notifications@github.com>
escreveu:
