### ISSUE TITLE
Outbound socket code

### ISSUE THREAD

**Issue by vadfabi** [EvoluxBR/greenswitch#26]
Does outbound socket server code is stable and production ready?
Does your block\nonblock session processing behavior blocks the main gevent loop and thus affects to new requests and socket server performance?

**Comment by italorossi** [comment]
It doesn't block the main greenlet, this should be able to handle a good amount of simultaneous calls. We never did a benchmark/load test, but it's in production right now to handle some custom routing logic and we're happy.

Also, we just added the ability to hot deploy code without killing active calls. The server tries to bind to a range of ports, first available is bound, and when receiving a SIGTERM we close the listening socket and wait for current calls to finish. This way you can proxy the server with HAproxy for example, just create the backends for the port range, it's nice!

**Comment by vadfabi** [comment]
I am looking a stable solution for Outbound Socket for FS to migrate from http/mod_xml_curl. 
You project seems to be right solution for me it small (unlike plivo) and clear, so let's try it.

**Comment by italorossi** [comment]
We'll update the documentations and do the merge ASAP. Please note that all the outbound socket implementation lives in a branch right now, there's a PR #14 opened!

**Comment by vadfabi** [comment]
thx! ;)
