### ISSUE TITLE
Code locking when requesting registers from a profile

### ISSUE THREAD

**Issue by Otoru** [EvoluxBR/greenswitch#37]
When using the greenswitch to execute the command `api sofia status profile internal reg` the code is simply locked.

In my terminal, I execute the following commands:
```python
In [1]: import greenswitch
In [2]: fs = greenswitch.InboundESL(host='127.0.0.1', port=8021, password='ClueCon')
In [3]: fs.connect()
In [4]: r = fs.send('api sofia status profile internal reg')
```
And my terminal is stopped on this line without allowing new inputs or outputs. I tried to wait for over thirty minutes and not a timeout happened.

To make sure that FreeSwitch was responding correctly, I used nmap on my machine and server. I could see my FreeSwitch answering the request correctly:

```text
T 2018/09/26 21:08:42.551400 127.0.0.1:8021 -> 127.0.0.1:40036 [AP] #4

Registrations:
=================================================================================================
Call-ID:    .1824570268-5060-1@BA.I.DA.GG
User:       .8568@pabx.voffice.com.br
Contact:    ."" <sip:8568@10.8.30.66:5060>
Agent:      .Grandstream GXP1625 1.0.1.12
Status:     .Registered(UDP)(unknown) EXP(2018-09-26 21:50:30) EXPSECS(2508)
Ping-Status:.Reachable
Ping-Time:.0.00
Host:       .PABX
IP:         .10.8.30.66
Port:       .5060
Auth-User:  .8568
Auth-Realm: .pabx.voffice.com.br
MWI-Account:.8568@pabx.voffice.com.br

...

Total items returned: 31
=================================================================================================
```

What could be happening? It is worth mentioning that in profiles where there are no registered extensions, this error does not occur.

**Comment by italorossi** [comment]
Taking a look at this now

**Comment by Otoru** [comment]
I have not forgotten `print (r.data)`. The interpreter hangs and does not allow the insertion of a new command until I press `ctrl+c`, generating a * KeyboardInterrupt* exception.

And about how to simulate, this only  happened on a freeswitch with more then 15 registered extensions.
