### ISSUE TITLE
Equivalent code

### ISSUE THREAD

**Issue by Otoru** [EvoluxBR/greenswitch#41]
For not knowing where to look for examples, I could not build an equivalent of the code below using greeswitch and I need help.

**Code**:
```python
import ESL
 
con = ESL.ESLconnection('localhost', '8021', 'ClueCon')
 
if con.connected():
    con.events('plain', 'all')
    while 1:
        e = con.recvEvent()
        if e:
            print e.serialize()
```

**Comment by diasbruno** [comment]
Hi @Otoru,

`greeswitch` allows you to register handlers for any event that freeswitch sends.

Here is one example for handling the `HEARTBEAT` event:

```python
import gevent
from greenswitch import InboundESL

con = InboundESL('127.0.0.1', 8021, 'ClueCon')

# handling an event 
con.register_handle('HEARTBEAT', lambda event: print('heartbeating', event))

con.connect()

event = con.send('event plain all')

if con.connected:
  while True:
    try:
      gevent.sleep(1) 
    except KeyboardInterrupt:
      con.stop()
      break

```

**Comment by diasbruno** [comment]
In case you meant "use greenswitch to wait for the next event", I believe that's not possible.

**Comment by Otoru** [comment]
The code above meets my need very well. A question for what is the `gevent.sleep(1)` statement in this code?

**Comment by diasbruno** [comment]
The `sleep` is to allow other resources "do some work".
