### ISSUE TITLE
args

### ISSUE THREAD

**Issue by CraftedCat** [EvoluxBR/greenswitch#50]
How to send some args to socket?
i used mod_commands, and use originate &(socket) via API

**Comment by italorossi** [comment]
You can use channel variables for that:

<action application="set" data="my_arg=my_value"/>
<action application="socket" data="127.0.0.1:5000 async full"/>

or originate {my_arg=my_value}user/1000 &socket(...)

You'll have access to my_arg at your python code.

**Comment by CraftedCat** [comment]
via sys.argv not accessable...

**Comment by italorossi** [comment]
Not in sys module, look at the channel variables.

**Comment by CraftedCat** [comment]
i set channel vars api originate {userid=userid, ignore_early_media=true...
how to print userid? in esl socket?

**Comment by CraftedCat** [comment]
api uuid_getvar <uuid> <name> ?

**Comment by CraftedCat** [comment]
help, please :(

**Comment by italorossi** [comment]
print(self.session_data.get('variable_ userid'))

**Comment by CraftedCat** [comment]
File "out_esl.py", line 50, in safe_run
    print(self.session_data.get('variable_ userid'))
AttributeError: 'MyApplication' object has no attribute 'session_data'

**Comment by italorossi** [comment]
Can you share your code? A gist would be sufficient.

**Comment by CraftedCat** [comment]
right code:
print(self.session.session_data.get('variable_ userid'))

but return None...
