### ISSUE TITLE
Design question

### ISSUE THREAD

**Issue by wilmarperez** [EvoluxBR/greenswitch#56]
Hi guys. 

Thanks for Greenswitch, it is very useful not to have to start from zero. I am just starting to get familiar with ESL and I have a design question:  if I am creating an IVR with Greeswitch. Would I create a single long app doing everything in the IVR flow or would I create small apps each one of them listening on a separate socket?

Thanks

**Comment by italorossi** [comment]
Start small and once you get bigger you can separate the apps in different modules. Depending on your workflow separating the apps on more than one server listening on dedicated sockets gives you ability to update code without affecting active calls on other apps. Hope this helps and sorry for the delay :).
