### ISSUE TITLE
Content-Lenght setup

### ISSUE THREAD

**Issue by elviroandres** [EvoluxBR/greenswitch#66]
I have an extension that cannot make calls, because it sends an altered value 

![image](https://user-images.githubusercontent.com/68777376/112983943-a5262700-9134-11eb-87b0-b42f7a70a854.png)

Is it possible to alter this value?

Thanks

**Comment by italorossi** [comment]
Hi @elviroandres ,

That should be fixed at your Microsip configuration, double-check the number of codecs you have enabled on it. A SDP of this size is not so common.

Could you explain how this is related to the Greenswitch project at all?
