### ISSUE TITLE
BACKGROUND_JOB event does not log any data

### ISSUE THREAD

**Issue by blaine12100** [EvoluxBR/greenswitch#69]
Hi

Currently, we originate calls with bgapi for which we need to use a BACKGROUND_JOB event which on normal Freeswitch CLI is enabled as "event plain BACKGROUND_JOB"

[https://freeswitch.org/confluence/display/FREESWITCH/Event+List](List of Freeswitch events)

The issue I am getting is that the event is being received by the handler but the event data is not getting logged

def test_function(event):
    message = "event message"
    message.format(**event.headers)
    

fs = greenswitch.InboundESL(host=<something>,port=<something>,password=<something>)
fs.connect()
fs.send("EVENT PLAIN ALL")
fs.register_handle("BACKGROUND_JOB", test_function)

while True:
    try:
        sleep(1)
    except:
         fs.stop()
          break

This example is similar to the example given by you (For the Sofia on register failure event)
Is there anything that we are doing wrong here?

**Comment by italorossi** [comment]
Maybe you need a print() at the bottom of test_function?

**Comment by blaine12100** [comment]
Got it
Was able to solve this issue by requesting only plain event data and parsing it.

Thanks for building this very useful library.
