### ISSUE TITLE
Catch all event handler to collect all events from FreeSWITCH

### ISSUE THREAD

**Issue by alochym01** [EvoluxBR/greenswitch#9]
hi list

i want to collect all events of freeswitch

i read the example but

`fs.register_handle('sofia::register_failure', on_sofia_register_failure)` 

show only the register failure event

how to collect all events and then send them to center logs server

thank you

**Comment by italorossi** [comment]
Hi!

First you need to listen to all events like

fs.send('events plain ALL')

and register your handlers to the events like you did with sofia one.

FreeSWITCH has a bunch os events, you may need to take a look at FS Docs.

**Comment by alochym01** [comment]
Hi

there is a lot of event lists to name few of them
[https://freeswitch.org/confluence/display/FREESWITCH/Event+List#EventList-Channelevents](url)
[https://freeswitch.org/confluence/display/FREESWITCH/Event+List#EventList-Customevents](url)
[https://freeswitch.org/confluence/display/FREESWITCH/Event+List](url)

In the example code , there is only register handle specific event('sofia::register_failure')

how do i do for all events like

def on_sofia_register_failure(event):
    message = 'event message'
    print(message.format(**event.headers))

fs.register_handle('*::*', on_sofia_register_failure)

thank you

**Comment by italorossi** [comment]
I think we can add a catch all event handler for that, what you think?

**Comment by alochym01** [comment]
yeah, that would be nice a feature :+1: +1:

**Comment by italorossi** [comment]
This is being covered on the outbound-socket branch.

**Comment by italorossi** [comment]
Current master implements it.
